import type { Metadata } from "next";
import Link from "next/link";
import { BrandCard } from "@/components/BrandCard";
import { brands } from "@/data/brands";
import { stores } from "@/data/stores";

export const metadata: Metadata = { title: "Anime Dolls World — каталог аниме- и фурри-кукол", description: "Независимый справочник брендов, магазинов, аниме- и фурри-кукол, выбора и ухода.", alternates: { canonical: "/" } };

export default function Home() {
  return <>
    <section className="hero"><div className="container"><div className="hero-content"><p className="eyebrow">Независимый каталог · 18+</p><h1>Anime Dolls <span>World</span></h1><p className="lede">Каталог аниме- и фурри-кукол, брендов, магазинов и спокойных, проверяемых материалов по выбору и уходу.</p><div className="hero-actions"><Link className="button primary" href="/brands/">Смотреть бренды</Link><Link className="button secondary" href="/stores/">Где купить</Link><Link className="button secondary" href="/anime-dolls/">Аниме-куклы</Link><Link className="button secondary" href="/furry-dolls/">Фурри-куклы</Link></div><div className="trust-row"><span>Без откровенного контента</span><span>Данные из открытых источников</span><span>Не магазин</span></div></div></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Навигация по миру кукол</p><h2>Начните с нужного направления</h2></div><p>Разделяем категории и справочные материалы, чтобы сравнивать бренды было проще.</p></div><div className="direction-grid"><Link className="direction-card" href="/anime-dolls/"><span className="number">01</span><div><h3>Аниме-куклы</h3><p>Стилизованные модели, материалы и важные критерии выбора.</p></div></Link><Link className="direction-card" href="/furry-dolls/"><span className="number">02</span><div><h3>Фурри-куклы</h3><p>Антропоморфные и фантазийные линейки в отдельном каталоге.</p></div></Link><Link className="direction-card" href="/buying/"><span className="number">03</span><div><h3>Выбор и покупка</h3><p>Проверки до заказа, сравнение материалов и безопасность сделки.</p></div></Link></div></div></section>
    <section className="section alt"><div className="container"><div className="section-head"><div><p className="eyebrow">Популярные производители</p><h2>Бренды каталога</h2></div><Link href="/brands/" className="text-link">Все бренды <span>→</span></Link></div><div className="brand-grid">{brands.slice(0,6).map(brand => <BrandCard key={brand.slug} brand={brand} />)}</div></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Покупка</p><h2>Магазины и площадки</h2></div><p>Нейтральные ориентиры без обещаний по ценам, срокам и наличию.</p></div><div className="store-grid">{stores.map(store => <Link href={`/stores/${store.slug}/`} className="store-card" key={store.slug}><span className="tag">{store.eyebrow}</span><h3>{store.name}</h3><p>{store.summary}</p><span className="text-link">Открыть памятку →</span></Link>)}</div></div></section>
    <section className="section alt"><div className="container"><div className="placeholder-band"><span className="placeholder-icon">✦</span><p className="eyebrow">Будущее обновление</p><h2>Новые модели появятся здесь</h2><p className="lede" style={{margin:"0 auto"}}>Галереи и карточки моделей будут добавлены после проверки первичных источников и прав на изображения.</p></div></div></section>
    <div className="disclaimer-strip"><div className="container"><span>ⓘ</span><span>Сайт носит справочный характер, не продаёт товары и не гарантирует актуальность условий сторонних площадок. Перед покупкой проверяйте данные у производителя или продавца.</span></div></div>
  </>;
}
