import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { siteConfig } from "@/data/site";

const routeSteps = [
  ["Определить желаемый образ", "Решите, нужен ли аниме-, фурри-, полноразмерный или компактный формат."],
  ["Выбрать материал", "Сопоставьте свойства TPE и силикона с ожидаемыми ощущениями и уровнем ухода."],
  ["Установить допустимую массу", "Оцените не только рост, но и возможность безопасно перемещать изделие."],
  ["Проверить механику и опции", "Уточните каркас, пальцы, стопы, соединение головы и диапазон суставов."],
  ["Сравнить бренды и продавцов", "Изучайте конкретную модель, реальные фотографии и прозрачность условий."],
  ["Зафиксировать комплектацию письменно", "Сохраните согласованные параметры, стоимость, доставку и порядок решения проблем."],
];
const formats = [
  ["Аниме", "Стилизованная внешность, крупные глаза, выраженный образ, широкий выбор париков, одежды и персонажных деталей."],
  ["Фурри", "Фэнтезийные и антропоморфные образы. Заранее уточняйте устройство головы, комплект и декоративные элементы."],
  ["Полноразмерная модель", "Наиболее требовательный формат по массе, хранению, переноске, очистке и подготовке помещения."],
  ["Компактная модель", "Часто удобнее в перемещении и хранении, но реальную массу всё равно нужно проверять у конкретной модели."],
  ["Торс", "Формат без полного тела со своей спецификой хранения, очистки и переноски."],
];
const tpeFeatures = ["обычно мягче и эластичнее", "быстрее нагревается от прикосновения", "после очистки может ощущаться более липким", "часто нуждается в лёгком припудривании", "легче впитывает запахи и некоторые загрязнения", "чувствительнее к агрессивной химии", "обычно проще поддаётся локальному ремонту", "нередко доступнее по цене"];
const siliconeFeatures = ["обычно плотнее", "стабильнее удерживает форму", "часто даёт более выраженную детализацию", "меньше склонен к липкости после очистки", "обычно требует меньше обслуживания поверхности", "при сопоставимом размере часто тяжелее TPE", "ремонт может требовать специальных составов", "не требует масел для регулярного ухода"];
const heightGroups = [["140–150 см", "Компактный полноразмерный диапазон. Часто удобнее для первого опыта, но массу нужно проверять отдельно."], ["150–165 см", "Распространённый средний диапазон с широким выбором моделей и комплектаций."], ["165 см и выше", "Наиболее требовательный формат по перемещению, хранению и бытовой логистике."]];
const weightGroups = [["До 30 кг", "Для многих владельцев наиболее управляемый диапазон."], ["30–35 кг", "Требует подготовки и продуманного способа перемещения."], ["Более 35 кг", "Становится заметной физической нагрузкой."], ["40 кг и более", "Может потребовать помощника, тележку, подъёмное устройство или постоянное место хранения."]];
const deliveryChecks = ["чистую массу изделия", "массу вместе с коробкой", "размеры упаковки", "наличие деревянной обрешётки", "точку завершения доставки", "помощь при переноске", "место распаковки", "подготовленное место хранения"];
const skeletonChecks = ["тип каркаса", "подвижность плеч", "диапазон движения шеи", "конструкцию позвоночника", "подвижность таза", "конструкцию кистей", "тип пальцев", "наличие стоячих стоп", "допустимость длительного стояния", "ограничения суставов", "возможность ремонта или замены деталей"];
const appearanceChecks = ["точный код головы", "совместимость головы и тела", "тип соединения", "материал головы", "цвет и форму глаз", "сменность глаз", "тип парика", "наличие формованной причёски", "входит ли одежда", "входящие аксессуары", "соответствие промообраза реальной комплектации"];
const modelPriorities = ["конкретная модель", "используемый материал", "производственная партия", "конструкция", "продавец", "комплектация", "реальные фотографии готового изделия"];
const photoRequests = ["реальные фотографии модели", "фотографии со склада", "снимки с производства", "готовый заказ перед отправкой", "лицо и макияж крупным планом", "тело", "подтверждение выбранных опций", "упаковку при необходимости"];
const warningSignals = ["продавец избегает конкретных ответов", "не показывает реальные фотографии", "использует только рекламные изображения", "торопит с оплатой", "характеристики выглядят неправдоподобно", "комплектация не зафиксирована", "цена заметно ниже рынка без объяснения", "условия меняются после согласования"];
const safetyRules = ["не отправлять деньги по внезапно изменившимся реквизитам", "не оплачивать до подтверждения комплектации", "проверять номер заказа", "проверять итоговую сумму", "сохранять переписку", "сохранять инвойс", "проверять актуальные правила площадки", "не полагаться на устные обещания", "не считать скидку доказательством надёжности"];
const writtenChecks = ["бренд", "модель тела", "модель головы", "материал тела", "материал головы", "цвет кожи", "макияж", "глаза", "парик", "одежда", "аксессуары", "рост", "чистая масса", "масса с упаковкой", "конструкция каркаса", "пальцы", "стоячие стопы", "дополнительные опции", "итоговая стоимость", "стоимость доставки", "срок изготовления", "заводские фотографии", "правила исправления ошибок", "условия возврата", "порядок подачи претензии"];
const finalAlgorithm = ["Выбрать образ", "Определить материал", "Установить предел массы", "Проверить каркас", "Уточнить комплектацию", "Изучить конкретную модель", "Проверить продавца", "Запросить реальные фотографии", "Зафиксировать заказ письменно", "Продумать доставку и хранение", "Снять распаковку на видео"];

export function BuyingGuide() {
  const webPageJsonLd = { "@context": "https://schema.org", "@type": "WebPage", name: "Как выбрать аниме-куклу: TPE, силикон, вес и покупка", description: "Практическое руководство по выбору аниме-куклы: TPE или силикон, рост и вес, каркас, комплектация, проверка продавца, доставка и получение заказа.", url: `${siteConfig.url}/buying/`, isPartOf: { "@type": "WebSite", name: siteConfig.name, url: siteConfig.url } };
  return <>
    <section className="page-hero buying-hero buying-page-hero"><div className="container"><Breadcrumbs items={[{ label: "Выбор и покупка" }]} /><p className="eyebrow">Практический маршрут · 18+</p><h1>Как выбрать аниме-куклу</h1><p className="lede">Материал, размер, масса, каркас, комплектация и проверка продавца — основные параметры, которые стоит оценить до оплаты.</p><p className="buying-hero-note">Красивые фотографии показывают внешний образ модели, но повседневный опыт владения намного сильнее зависит от массы изделия, свойств материала, конструкции и условий заказа.</p><div className="buying-tags">{["TPE или силикон", "Размер и масса", "Каркас", "Проверка продавца", "Комплектация", "Получение заказа"].map((tag) => <span key={tag}>{tag}</span>)}</div><div className="buying-actions"><Link className="button primary" href="/brands/">Смотреть бренды</Link><Link className="button secondary" href="/stores/">Варианты покупки</Link></div></div></section>
    <nav className="guide-anchor-nav" aria-label="Разделы страницы выбора"><div className="container">{[["#route","Маршрут"],["#format","Формат"],["#materials","Материалы"],["#weight","Масса"],["#mechanics","Каркас"],["#seller","Продавец"],["#receiving","Получение"]].map(([href,label])=><a href={href} key={href}>{label}</a>)}</div></nav>
    <article className="buying-profile">
      <section className="section" id="route"><div className="container"><div className="section-head"><div><p className="eyebrow">Шесть решений</p><h2>Быстрый маршрут выбора</h2></div><p>Двигайтесь от бытовых ограничений к внешнему образу и условиям сделки.</p></div><ol className="buying-route-grid">{routeSteps.map(([title,text],index)=><li key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
      <section className="section alt" id="format"><div className="container"><div className="section-head"><div><p className="eyebrow">Первое ограничение</p><h2>Сначала определите формат</h2></div><p>Поймите, какой тип изделия подходит по образу, пространству и повседневному обращению.</p></div><div className="buying-format-grid">{formats.map(([title,text])=><section key={title}><h3>{title}</h3><p>{text}</p></section>)}</div></div></section>
      <section className="section" id="materials"><div className="container"><div className="section-head"><div><p className="eyebrow">Сравнение материалов</p><h2>TPE или силикон</h2></div><p>Свойства зависят от конкретной смеси и модели, поэтому ориентиры не являются абсолютными.</p></div><div className="buying-material-grid"><section className="buying-material-card tpe"><span>TPE</span><ul>{tpeFeatures.map(item=><li key={item}>{item};</li>)}</ul><div><strong>Кому может подойти</strong><p>Тем, кому важна мягкость и кто готов уделять поверхности больше внимания.</p></div></section><section className="buying-material-card silicone"><span>Силикон</span><ul>{siliconeFeatures.map(item=><li key={item}>{item};</li>)}</ul><div><strong>Кому может подойти</strong><p>Тем, кому важны детализация, стабильность формы и менее трудоёмкий уход.</p></div></section></div><div className="notice">Помимо классического TPE и силикона, у отдельных производителей встречаются фирменные обозначения S-TPE и STPE, а также варианты силикона с названиями ultra-soft silicone, hyper-soft silicone и другими коммерческими обозначениями. Их свойства могут заметно различаться, поэтому сравнивать следует конкретные материалы и модели, а не только общую категорию. Эти обозначения нельзя автоматически считать взаимозаменяемыми.</div><div className="buying-conclusion">Идеального материала не существует. Выбирайте не по принципу «дороже значит лучше», а по ожидаемым ощущениям, допустимому уходу, массе модели и условиям хранения.</div></div></section>
      <section className="section alt" id="weight"><div className="container"><div className="section-head"><div><p className="eyebrow">Бытовая логистика</p><h2>Масса важнее одного только роста</h2></div><p>С размером обычно растут масса, нагрузка на каркас и сложность переноски.</p></div><div className="buying-height-grid">{heightGroups.map(([title,text])=><section key={title}><h3>{title}</h3><p>{text}</p></section>)}</div><div className="buying-weight-panel"><div><p className="eyebrow">Почему тяжелее ожидаемого</p><h3>Масса распределена по всему телу</h3><p>Модель не помогает удерживать равновесие, поэтому перемещать её сложнее, чем обычный предмет той же массы.</p></div><div className="buying-weight-grid">{weightGroups.map(([title,text])=><div key={title}><strong>{title}</strong><p>{text}</p></div>)}</div></div><div className="notice">Это не универсальные медицинские или физические нормы. Возможности каждого владельца индивидуальны.</div></div></section>
      <section className="section"><div className="container buying-two-column"><section className="buying-content-card"><p className="eyebrow">До оплаты</p><h2>Продумайте доставку</h2><ul className="buying-check-grid">{deliveryChecks.map(item=><li key={item}>{item}</li>)}</ul><div className="buying-emphasis"><strong>Не ориентируйтесь только на массу модели</strong><span>Коробка, упаковка, аксессуары и деревянная обрешётка могут заметно увеличить общую массу отправления.</span></div></section><section className="buying-content-card" id="mechanics"><p className="eyebrow">Практика позирования</p><h2>Каркас определяет опыт</h2><p>Внутренняя металлическая конструкция влияет на диапазон поз, устойчивость суставов, перемещение и долговечность.</p><ul className="buying-check-grid">{skeletonChecks.map(item=><li key={item}>{item}</li>)}</ul></section></div></section>
      <section className="section alt"><div className="container"><div className="buying-mechanics-grid"><section><h3>Пальцы</h3><p>Проволочная конструкция проще, но требует осторожности. Шарнирные варианты могут расширять возможности, если подтверждены для модели.</p></section><section><h3>Стоячие стопы</h3><p>Помогают установить модель вертикально, но не делают длительное хранение без поддержки автоматически безопасным.</p></section><section><h3>Подвижные плечи</h3><p>Расширяют позирование, однако нужны не всем и могут усложнять конструкцию.</p></section></div><p className="buying-small-note">Маркетинговое название каркаса само по себе не доказывает качество.</p></div></section>
      <section className="section"><div className="container buying-two-column"><section className="buying-content-card"><p className="eyebrow">Готовый образ</p><h2>Голова, глаза, парик и комплект</h2><ul className="buying-check-grid">{appearanceChecks.map(item=><li key={item}>{item}</li>)}</ul><div className="notice">На промофотографиях могут быть парик, одежда и аксессуары, которые не входят в базовую комплектацию.</div></section><section className="buying-content-card"><p className="eyebrow">Оценка производителя</p><h2>Бренд — ориентир, но не гарантия</h2><p>Название помогает изучать рынок, но итог зависит от совокупности факторов:</p><div className="buying-pill-list">{modelPriorities.map(item=><span key={item}>{item}</span>)}</div><Link className="text-link" href="/brands/">Смотреть каталог брендов</Link></section></div></section>
      <section className="section alt" id="seller"><div className="container"><div className="section-head"><div><p className="eyebrow">Прозрачность сделки</p><h2>Не решайте только по студийным фото</h2></div><p>Чем меньше прозрачности, тем выше риск.</p></div><div className="buying-seller-grid"><section><h3>Что запросить</h3><ul>{photoRequests.map(item=><li key={item}>{item}</li>)}</ul></section><section className="risk"><h3>Тревожные сигналы</h3><ul>{warningSignals.map(item=><li key={item}>{item}</li>)}</ul></section></div></div></section>
      <section className="section"><div className="container buying-two-column"><section className="buying-content-card"><p className="eyebrow">История сделки</p><h2>Безопасность покупки</h2><p>На торговой площадке полезно сохранять переписку и оплату внутри её системы, чтобы история заказа оставалась доступной.</p><ul>{safetyRules.map(item=><li key={item}>{item};</li>)}</ul><p className="buying-small-note">Механизмы площадки не означают гарантированный возврат средств.</p></section><section className="buying-content-card"><p className="eyebrow">Фиксация заказа</p><h2>Что подтвердить письменно</h2><div className="buying-written-grid">{writtenChecks.map(item=><span key={item}>{item}</span>)}</div></section></div></section>
      <section className="section alt" id="receiving"><div className="container"><div className="section-head"><div><p className="eyebrow">Контроль доставки</p><h2>Получение и первичная проверка</h2></div><p>При проблеме быстро свяжитесь с продавцом и сохраните материалы проверки.</p></div><div className="buying-receive-grid"><section><span>01</span><h3>Перед вскрытием</h3><ul><li>Осмотрите коробку.</li><li>Зафиксируйте повреждения.</li><li>Начните непрерывную видеозапись.</li></ul></section><section><span>02</span><h3>Во время распаковки</h3><ul><li>Снимайте без склеек.</li><li>Зафиксируйте комплект.</li><li>Не выбрасывайте упаковку сразу.</li></ul></section><section><span>03</span><h3>Первичный осмотр</h3><ul><li>Проверьте поверхность, лицо, макияж и мягкие зоны.</li><li>Осмотрите пальцы, стопы, шею и суставы.</li><li>Сверьте аксессуары и комплектацию.</li></ul></section></div></div></section>
      <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Перед заказом</p><h2>Итоговый алгоритм</h2></div><p>Одиннадцать шагов от идеи до распаковки.</p></div><ol className="buying-final-grid">{finalAlgorithm.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol><div className="buying-next"><div><p className="eyebrow">Продолжить подготовку</p><h3>После покупки: правила ухода</h3></div><nav aria-label="Связанные материалы"><Link href="/care/">Перейти к уходу</Link><Link href="/brands/">Бренды</Link><Link href="/stores/">Магазины</Link></nav></div></div></section>
      <section className="section alt"><div className="container"><div className="buying-disclaimer"><p className="eyebrow">Независимый справочник</p><h2>Важное предупреждение</h2><p>Anime Dolls World публикует этот материал исключительно в справочных целях.</p><ul><li>Сайт не является продавцом.</li><li>Не участвует в оплате.</li><li>Не гарантирует характеристики моделей.</li><li>Не отвечает за самостоятельные решения покупателя.</li><li>Не подтверждает заявления производителей независимо.</li></ul><p><strong>Все параметры проверяйте в карточке конкретной модели и подтверждайте у продавца до оплаты.</strong></p></div></div></section>
    </article>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(webPageJsonLd)}} />
  </>;
}
