import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { siteConfig } from "@/data/site";

const principles = ["бережный уход предпочтительнее агрессивной очистки", "не следует сильно тереть материал", "после очистки изделие нужно полностью просушивать", "новое средство проверяется на незаметном участке", "TPE и силикон требуют разных средств", "прямой солнечный свет вреден обоим материалам", "высокая температура вредна обоим материалам", "длительное давление может менять форму мягких зон", "слишком частая очистка создаёт дополнительный износ"];
const preparation = ["чистые мягкие полотенца", "мягкая губка", "мягкая салфетка", "тёплая, но не горячая вода", "мягкое нейтральное средство", "инструменты для труднодоступных мест", "безопасное место для сушки", "специальная пудра для кукол, если она нужна TPE-модели", "чистое мягкое основание"];
const cleaningSteps = ["Снимите одежду и аксессуары.", "Уберите пыль мягкой сухой салфеткой.", "Используйте тёплую воду и немного мягкого средства.", "Очищайте без сильного трения.", "Особенно бережно обрабатывайте лицо, макияж и окрашенные участки.", "Удалите остатки средства чистой водой или влажной салфеткой.", "Промокните поверхность полотенцем.", "Полностью высушите перед одеждой и хранением."];
const cleaningAvoid = ["кипяток", "жёсткие щётки", "абразивные материалы", "растворители", "хлор", "агрессивные пятновыводители", "длительное замачивание", "сильное растягивание поверхности"];
const tpeCare = ["после очистки поверхность может стать более липкой", "материал нужно полностью высушивать", "после высыхания может понадобиться лёгкое припудривание", "легче впитывает красители и запахи", "чувствительнее к агрессивной химии", "небольшое количество совместимого минерального масла иногда используют локально при сильном загрязнении", "избыток масла может ухудшить вид и свойства поверхности"];
const siliconeCare = ["обычно не требует припудривания всей поверхности", "не нуждается в минеральном или детском масле", "масла могут повредить материал или окрашивание", "макияж и пигментированные участки очищают особенно мягко", "локальные загрязнения удаляют только совместимыми с силиконом средствами"];
const dryingSurface = ["промокнуть влагу", "не тереть полотенцем", "оставить в проветриваемом помещении", "проверить складки", "осмотреть труднодоступные участки", "не надевать одежду на влажную поверхность", "не убирать влажную модель в закрытый шкаф"];
const dryingTools = ["мягкие впитывающие тампоны", "специальные палочки", "подходящие щадящие сушильные приспособления", "слабый поток воздуха", "аквариумный компрессор с чистой трубкой без нагрева и с осторожностью"];
const powderSteps = ["Убедитесь, что поверхность полностью сухая.", "Нанесите немного специальной пудры для кукол.", "Распределите мягкой кистью или чистой салфеткой.", "Не оставляйте толстых комков.", "Удалите излишки."];
const faceRules = ["не тереть лицо", "не использовать спирт", "не использовать растворители", "не оставлять лицо прижатым к ткани", "избегать длительного контакта с влажным париком", "учитывать конструкцию головы при замене глаз", "не давить на глазницы", "проверять совместимость клея для ресниц", "при сомнениях следовать инструкции производителя"];
const wigRules = ["использовать защитную светлую шапочку", "не оставлять влажный парик на голове", "расчёсывать отдельно от куклы", "начинать с концов", "не тянуть за основание", "хранить отдельно на подставке или в свободной упаковке", "проверять поверхность головы на окрашивание"];
const riskyClothes = ["чёрные джинсы", "тёмные чулки", "необработанная синтетика", "дешёвые яркие ткани", "влажная одежда", "длительное хранение в одном тёмном образе"];
const clothingSteps = ["Несколько раз постирать вещь отдельно.", "Проверить, окрашивает ли она воду.", "Проверить белой салфеткой.", "Провести тест на совместимом материале или незаметном участке.", "Использовать светлый нижний слой.", "Не оставлять новую тёмную одежду надолго.", "Регулярно осматривать зоны контакта."];
const stainSteps = ["сразу снять окрашивающую одежду", "не растирать пятно", "сфотографировать участок", "проверить рекомендации производителя", "начать с самого мягкого совместимого метода", "тестировать на незаметном месте", "не смешивать химические составы", "остановиться при изменении цвета или текстуры"];
const storageGood = ["сухое помещение", "стабильная комнатная температура", "отсутствие прямого солнца", "вентиляция", "мягкая чистая опора", "минимум постоянного давления", "нейтральное положение суставов", "отсутствие сильного натяжения", "поддержка мягких зон при необходимости"];
const storageBad = ["жара", "мороз", "резкие перепады температуры", "высокая влажность", "прямой солнечный свет", "батарея или обогреватель рядом", "жёсткий пол", "длительное положение сидя", "тесный герметичный контейнер", "долгое хранение в тёмной одежде"];
const positions = [["Лёжа", "Понятный вариант на ровной мягкой поверхности. Избегайте постоянного давления на одно место."], ["Подвес", "Допустим только со штатной конструкцией и подходящим креплением без давления жёсткого крюка на материал."], ["Стоя", "Возможен для подходящей конструкции стоп и безопасной опоры. Риск падения всё равно сохраняется."], ["Сидя", "Не подходит для долгого хранения из-за постоянного давления на ягодицы, бёдра и складки."]];
const softZoneRules = ["поддерживать тяжёлую грудь в неудобной позе", "использовать мягкую светлую поддерживающую одежду", "не пережимать поверхность", "избегать острых складок", "не класть сверху тяжёлые предметы", "периодически проверять форму"];
const jointRules = ["менять позу медленно", "не выкручивать сустав через сопротивление", "поддерживать тяжёлую конечность второй рукой", "не использовать пальцы как опору", "не тянуть за кисти и стопы", "проверять натяжение материала вокруг суставов", "не оставлять конечности в предельном сгибе на месяцы", "прекратить движение при необычном хрусте", "не применять силу при заедании", "прекратить нагрузку при резком ослаблении сустава"];
const inspection = ["поверхность", "изменение цвета", "складки", "подмышки", "зоны трения", "пальцы", "стопы", "шея", "соединение головы", "макияж", "парик", "запах", "влажность", "одежда", "устойчивость суставов", "место хранения"];
const neverDo = ["использовать горячую воду", "сушить горячим феном", "использовать масла на силиконе", "применять растворители без подтверждённой совместимости", "надевать непроверенную тёмную одежду", "хранить влажную модель в шкафу", "оставлять под прямым солнцем", "держать долго в крайней позе", "тянуть за пальцы", "силой разрабатывать заклинивший сустав", "смешивать чистящие средства", "выполнять сложный ремонт без понимания материала"];
const askForHelp = ["разрыв рядом с суставом", "повреждение внутреннего каркаса", "резкое ослабление сустава", "запах, похожий на коррозионный", "длительная влажность внутри", "изменение структуры поверхности", "повреждение макияжа", "глубокое окрашивание", "трещина в зоне высокой нагрузки", "сомнение в совместимости ремонтного состава"];

export function CareGuide() {
  const webPageJsonLd = { "@context": "https://schema.org", "@type": "WebPage", name: "Уход за аниме-куклой из TPE и силикона", description: "Практическая памятка по уходу за аниме-куклой: очистка и сушка, пудрение TPE, уход за силиконом, одежда, окрашивание, парик и безопасное хранение.", url: `${siteConfig.url}/care/`, isPartOf: { "@type": "WebSite", name: siteConfig.name, url: siteConfig.url } };
  return <>
    <section className="page-hero care-hero"><div className="container"><Breadcrumbs items={[{ label: "Уход" }]} /><p className="eyebrow">Практическая памятка владельца · 18+</p><h1>Уход за аниме-куклой</h1><p className="lede">Очистка, сушка, пудрение, защита от окрашивания и хранение без лишней нагрузки на материал.</p><p className="care-hero-note">Долговечность зависит не только от цены или бренда. Регулярный бережный уход и правильное хранение напрямую влияют на состояние материала и конструкции.</p><div className="care-tags">{["Очистка", "Сушка", "TPE", "Силикон", "Пудрение", "Одежда", "Хранение"].map(tag=><span key={tag}>{tag}</span>)}</div></div></section>
    <nav className="guide-anchor-nav care-anchor-nav" aria-label="Разделы страницы ухода"><div className="container">{[["#principles","Основы"],["#cleaning","Очистка"],["#materials-care","Материалы"],["#drying","Сушка"],["#clothing","Одежда"],["#storage","Хранение"],["#inspection","Осмотр"]].map(([href,label])=><a href={href} key={href}>{label}</a>)}</div></nav>
    <article className="care-profile">
      <section className="section" id="principles"><div className="container"><div className="care-principle-panel"><div><p className="eyebrow">Главная цель</p><h2>Удалить загрязнение, не повреждая поверхность</h2><p>Приоритет — совместимость средства, мягкое воздействие и полное высыхание.</p></div><ul>{principles.map(item=><li key={item}>{item};</li>)}</ul></div></div></section>
      <section className="section alt"><div className="container care-two-column"><section className="care-content-card"><p className="eyebrow">Рабочее место</p><h2>Подготовка</h2><ul className="care-check-grid">{preparation.map(item=><li key={item}>{item}</li>)}</ul><div className="notice">Не кладите модель на грязный пол или жёсткую поверхность. Подготовьте большую кровать, мягкий мат, толстое одеяло или другое чистое основание.</div></section><section className="care-content-card" id="cleaning"><p className="eyebrow">Последовательность</p><h2>Общая очистка поверхности</h2><ol className="care-numbered-list">{cleaningSteps.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol></section></div></section>
      <section className="section"><div className="container"><div className="care-avoid-panel"><div><p className="eyebrow">Во время очистки</p><h2>Не использовать</h2></div><div>{cleaningAvoid.map(item=><span key={item}>{item}</span>)}</div></div><p className="care-small-note">Рекомендации производителя конкретной модели имеют приоритет.</p></div></section>
      <section className="section alt" id="materials-care"><div className="container"><div className="section-head"><div><p className="eyebrow">Разные поверхности</p><h2>TPE и силикон: разный уход</h2></div><p>Средство выбирают по материалу конкретной модели.</p></div><div className="care-material-grid"><section className="care-material-card tpe"><span>TPE</span><ul>{tpeCare.map(item=><li key={item}>{item};</li>)}</ul><div className="notice">Используйте только совместимое с TPE средство. Не заливайте поверхность маслом и не применяйте его как универсальный регулярный уход.</div></section><section className="care-material-card silicone"><span>Силикон</span><ul>{siliconeCare.map(item=><li key={item}>{item};</li>)}</ul><div className="care-oil-warning">Не используйте масла для ухода за силиконовой куклой.</div></section></div></div></section>
      <section className="section" id="drying"><div className="container"><div className="section-head"><div><p className="eyebrow">Критический этап</p><h2>Полная сушка</h2></div><p>Не надевайте одежду и не закрывайте модель в шкафу, пока остаётся влага.</p></div><div className="care-drying-grid"><section><h3>После очистки поверхности</h3><ul>{dryingSurface.map(item=><li key={item}>{item}</li>)}</ul></section><section><h3>Для полостей и каналов</h3><ul>{dryingTools.map(item=><li key={item}>{item}</li>)}</ul></section></div><div className="care-emphasis"><strong>Без нагрева</strong><span>Не используйте горячий фен и сильный нагретый воздух. Если полости имеют доступ к металлическому каркасу, не заливайте воду глубоко и особенно тщательно контролируйте сушку.</span></div></div></section>
      <section className="section alt"><div className="container care-two-column"><section className="care-content-card"><p className="eyebrow">Только после высыхания</p><h2>Пудрение TPE</h2><p>Тонкий слой специальной пудры может уменьшить липкость и вернуть поверхности более сухое ощущение.</p><ol className="care-numbered-list compact">{powderSteps.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol><ul><li>Используйте специальную пудру для кукол.</li><li>Не вдыхайте пыль.</li><li>Не наносите на влажную поверхность.</li><li>Не считайте детскую присыпку универсальной заменой без проверки состава.</li><li>Силикон обычно не нуждается в таком уходе.</li></ul></section><section className="care-content-card"><p className="eyebrow">Деликатные элементы</p><h2>Лицо, макияж и глаза</h2><ul className="care-check-grid">{faceRules.map(item=><li key={item}>{item}</li>)}</ul></section></div></section>
      <section className="section"><div className="container care-wig-panel"><div><p className="eyebrow">Съёмный образ</p><h2>Парик</h2><p>Парик может переносить краситель, спутываться и повреждать макияж при длительном трении.</p></div><ul>{wigRules.map(item=><li key={item}>{item}</li>)}</ul></div></section>
      <section className="section alt" id="clothing"><div className="container"><div className="care-clothing-panel"><div><p className="eyebrow">Главный риск</p><h2>Одежда и окрашивание</h2><p>Тёмные и насыщенные ткани могут переносить краситель на TPE и силикон.</p><h3>Наиболее рискованны</h3><div className="care-risk-tags">{riskyClothes.map(item=><span key={item}>{item}</span>)}</div></div><div><h3>Проверка новой одежды</h3><ol className="care-numbered-list compact">{clothingSteps.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol></div></div><p className="care-small-note">Светлая домашняя одежда обычно безопаснее для длительного хранения, но любую новую ткань всё равно лучше проверять.</p><div className="notice">Пищевая плёнка не подходит для постоянного хранения. Защитный барьер не должен сдавливать материал, задерживать влагу или оставаться надолго без проверки.</div></div></section>
      <section className="section"><div className="container care-two-column"><section className="care-content-card"><p className="eyebrow">Локальное окрашивание</p><h2>Если появилось пятно</h2><p>Сначала определите материал модели и вероятный источник окрашивания.</p><ul className="care-check-grid">{stainSteps.map(item=><li key={item}>{item}</li>)}</ul><div className="notice">Бензоилпероксид, сильные растворители и экспериментальные методы способны изменить пигмент или поверхность и не являются универсально безопасным решением.</div></section><section className="care-content-card"><p className="eyebrow">Без экспериментов</p><h2>Сначала совместимость</h2><p>Не смешивайте составы и не начинайте с сильного воздействия. При любом изменении цвета, блеска или текстуры прекратите обработку.</p><p className="care-small-note">Подробные медицинские схемы здесь не приводятся.</p></section></div></section>
      <section className="section alt" id="storage"><div className="container"><div className="section-head"><div><p className="eyebrow">Долгий горизонт</p><h2>Безопасное хранение</h2></div><p>Снижайте постоянное давление, натяжение материала и воздействие среды.</p></div><div className="care-storage-grid"><section className="good"><h3>Подходящие условия</h3><ul>{storageGood.map(item=><li key={item}>{item}</li>)}</ul></section><section className="bad"><h3>Опасные условия</h3><ul>{storageBad.map(item=><li key={item}>{item}</li>)}</ul></section></div><div className="care-position-grid">{positions.map(([title,text])=><section key={title}><h3>{title}</h3><p>{text}</p></section>)}</div><p className="care-small-note">При длительном хранении положение желательно периодически менять.</p></div></section>
      <section className="section"><div className="container care-two-column"><section className="care-content-card"><p className="eyebrow">Распределение нагрузки</p><h2>Поддержка мягких участков</h2><p>Мягкие зоны особенно чувствительны к длительному давлению, растяжению и неправильной опоре.</p><ul>{softZoneRules.map(item=><li key={item}>{item};</li>)}</ul></section><section className="care-content-card"><p className="eyebrow">Без усилия</p><h2>Суставы и пальцы</h2><ul>{jointRules.map(item=><li key={item}>{item};</li>)}</ul></section></div></section>
      <section className="section alt" id="inspection"><div className="container"><div className="section-head"><div><p className="eyebrow">Профилактика</p><h2>Регулярный осмотр</h2></div><p>Небольшую проблему обычно проще устранить на ранней стадии.</p></div><div className="care-inspection-grid">{inspection.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</div>)}</div></div></section>
      <section className="section"><div className="container care-two-column"><section className="care-stop-card"><p className="eyebrow">Стоп-лист</p><h2>Чего не делать</h2><ul>{neverDo.map(item=><li key={item}>Не {item}</li>)}</ul></section><section className="care-help-card"><p className="eyebrow">Нужна оценка</p><h2>Когда обращаться к продавцу или специалисту</h2><ul>{askForHelp.map(item=><li key={item}>{item}</li>)}</ul></section></div></section>
      <section className="section alt"><div className="container"><div className="section-head"><div><p className="eyebrow">Короткий цикл</p><h2>Краткая памятка</h2></div><p>Горизонтальные стрелки показывают последовательность действий.</p></div><div className="care-memo-grid"><section><h3>После использования</h3><p>Очистить при необходимости → полностью высушить → припудрить TPE при необходимости → осмотреть → убрать в безопасное положение.</p></section><section><h3>Перед хранением</h3><p>Снять рискованную одежду → проверить влажность → расправить складки → поддержать мягкие зоны → убрать от света и нагрева.</p></section><section><h3>Периодически</h3><p>Проверить материал → изменить положение → проветрить место хранения → осмотреть одежду и парик.</p></section></div><div className="care-next"><div><p className="eyebrow">Ещё выбираете модель?</p><h3>Сначала оцените материал, массу и продавца</h3></div><nav aria-label="Связанные материалы"><Link href="/buying/">Перейти к выбору</Link><Link href="/brands/">Бренды</Link><Link href="/stores/">Магазины</Link></nav></div></div></section>
      <section className="section"><div className="container"><div className="care-disclaimer"><p className="eyebrow">Справочная информация</p><h2>Важное предупреждение</h2><p>Anime Dolls World публикует общие практические рекомендации исключительно в справочных целях.</p><p>Свойства материалов, покрытий, макияжа и внутренних конструкций могут различаться. Инструкция конкретного производителя имеет приоритет.</p><ul><li>Сайт не отвечает за самостоятельное применение средств.</li><li>Не гарантирует совместимость химических составов.</li><li>Не рекомендует экспериментировать на видимых участках.</li><li>Не заменяет профессиональный ремонт.</li></ul></div></div></section>
    </article>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(webPageJsonLd)}} />
  </>;
}
