import { Breadcrumbs } from "@/components/Breadcrumbs";
import { siteConfig } from "@/data/site";

const officialUrl = "https://elsababedoll.com/";
const aliexpressUrl = "https://aliexpress.ru/store/1103338672?g=true&page=1&spm=a2g2w.detail.0.0.489052afRfYreY3";
const email = "service@elsababe.com";
const converterUrl = "https://www.sravni.ru/valjuty/konverter-yuanya-k-rublyu/";
const chinaTimeUrl = "https://24timezones.com/Китай/время";

const modelChecks = ["тело", "голова или face sculpt", "цвет глаз", "парик", "одежда", "дополнительные аксессуары", "возможные кастомные опции", "материал", "рост и вес"];
const emailDetails = ["ссылку на модель", "выбранное тело", "выбранную голову", "скриншоты", "список опций", "вопросы о комплектации", "вопросы о сроках и доставке"];
const configurationChecks = ["точное тело", "точную голову или face sculpt", "материал", "цвет кожи", "парик", "глаза", "одежду", "аксессуары", "кастомные изменения", "рост", "вес", "итоговую комплектацию", "итоговую стоимость", "стоимость доставки", "срок изготовления", "срок отправки", "способ оформления заказа"];
const priceFactors = ["тело", "голова или face sculpt", "материал", "дополнительные опции", "аксессуары", "кастомизация", "доставка", "курс валют", "условия продавца и торговой площадки"];
const paymentSteps = ["Покупатель согласовывает модель и итоговую конфигурацию.", "Продавец сообщает, какую карточку товара использовать.", "Покупатель создаёт заказ, но сразу его не оплачивает.", "Номер заказа передаётся продавцу.", "Продавец корректирует цену в соответствии с согласованной суммой.", "Покупатель проверяет изменённую цену.", "После проверки покупатель оплачивает заказ через AliExpress."];
const paymentWarnings = ["не оплачивайте заказ до изменения цены на согласованную", "проверьте итоговую сумму непосредственно перед оплатой", "убедитесь, что номер заказа совпадает", "неоплаченный заказ может быть активен ограниченное время", "порядок оформления может измениться из-за правил AliExpress", "продавец работает по китайскому времени, поэтому ответы могут приходить с задержкой"];
const safetyChecks = ["правильную карточку товара", "название магазина", "номер заказа", "согласованную сумму", "валюту", "адрес доставки", "комплектацию", "переписку с продавцом", "возможные комиссии", "условия отмены", "срок действия неоплаченного заказа"];
const productionChecks = ["ориентировочный срок изготовления", "дату начала производства", "возможность получения промежуточных подтверждений", "заводские фотографии", "срок передачи заказа перевозчику"];
const photoChecks = ["тело", "голову", "макияж", "цвет кожи", "глаза", "парик", "одежду", "аксессуары", "соответствие согласованной конфигурации", "отсутствие заметных внешних повреждений"];
const deliveryPreparation = ["вес изделия", "вес коробки", "габариты упаковки", "наличие деревянной обрешётки", "способ получения", "перенос коробки", "помощника или грузчика", "место распаковки", "место будущего хранения"];
const receivingChecks = ["осмотреть коробку до вскрытия", "сфотографировать упаковку", "зафиксировать вмятины, разрывы и следы намокания", "снять распаковку на видео", "проверить содержимое", "сверить тело, голову и аксессуары", "проверить видимые повреждения", "сохранить упаковку до окончания первичной проверки", "при проблеме сразу связаться с продавцом и службой доставки"];
const internalChecks = ["размеры внутреннего канала", "глубину", "различия между телами", "доступные варианты настройки", "возможность выбрать другую конфигурацию", "влияет ли выбранное тело на внутренние размеры"];
const finalChecks = ["официальное название модели", "код тела", "код головы", "материал", "рост", "вес", "цвет кожи", "макияж", "глаза", "парик", "одежду", "аксессуары", "кастомные опции", "внутренние размеры, если они важны", "итоговую комплектацию", "итоговую стоимость", "доставку", "срок изготовления", "заводские фотографии", "адрес", "способ оформления заказа", "изменение цены продавцом", "правила отмены и возврата", "действия при повреждении"];

export function ElsaBabeAliExpressGuide() {
  const webPageJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Как купить Elsa Babe через AliExpress",
    description: "Пошаговая инструкция по покупке аниме-куклы Elsa Babe через AliExpress: выбор модели, согласование комплектации, изменение цены, оплата, доставка и проверка заказа.",
    url: `${siteConfig.url}/stores/elsa-babe-aliexpress/`,
    isPartOf: { "@type": "WebSite", name: siteConfig.name, url: siteConfig.url },
  };

  return (
    <>
      <section className="page-hero elsa-hero">
        <div className="container">
          <Breadcrumbs items={[{ label: "Магазины", href: "/stores/" }, { label: "Elsa Babe через AliExpress" }]} />
          <div className="elsa-hero-grid">
            <div>
              <p className="eyebrow">Инструкция по покупке</p>
              <h1>Elsa Babe через AliExpress</h1>
              <p className="lede">Elsa Babe — бренд стилизованных аниме-кукол, в каталоге которого представлены силиконовые и TPE-модели. Материал конкретной конфигурации необходимо проверять перед заказом. На этой странице описан примерный порядок выбора модели, согласования комплектации и оформления индивидуального заказа через магазин бренда на AliExpress.</p>
              <p className="elsa-hero-note">Материал основан на практическом опыте взаимодействия с магазином и предназначен для совершеннолетних покупателей, которые впервые рассматривают такой способ заказа.</p>
              <div className="elsa-tags" aria-label="Темы инструкции">{["Elsa Babe", "Аниме-куклы", "Материал по модели", "AliExpress", "Индивидуальный заказ", "Россия"].map((tag) => <span key={tag}>{tag}</span>)}</div>
              <div className="elsa-hero-actions"><a className="button primary" href={officialUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть официальный сайт Elsa Babe в новой вкладке">Официальный сайт Elsa Babe</a><a className="button secondary" href={aliexpressUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть магазин Elsa Babe на AliExpress в новой вкладке">Магазин на AliExpress</a></div>
            </div>
            <div className="elsa-hero-mark" aria-hidden="true"><span>EB</span><small>Selection · Order · Delivery</small></div>
          </div>
        </div>
      </section>

      <article className="elsa-profile">
        <section className="section"><div className="container elsa-intro-grid"><div className="prose elsa-prose"><p className="eyebrow">Перед началом</p><h2>Как подойти к покупке</h2><p>В каталоге Elsa Babe представлены силиконовые и TPE-модели. Перед оформлением заказа необходимо согласовать с продавцом точный материал тела и головы выбранной конфигурации.</p><p>Порядок покупки может отличаться в зависимости от модели, действующих правил AliExpress и условий продавца. Поэтому все этапы необходимо подтверждать непосредственно перед оплатой.</p></div><aside className="elsa-summary-card"><p className="eyebrow">Ключевой принцип</p><strong>Сначала согласование — затем оплата</strong><p>Сохраните переписку, итоговую конфигурацию, сумму и номер заказа.</p></aside></div></section>

        <section className="section alt"><div className="container elsa-step-layout"><div className="elsa-step-number">01</div><div><p className="eyebrow">Первый шаг</p><h2>Выбор модели</h2><p>Сначала необходимо определиться с конфигурацией куклы.</p><ul className="elsa-option-grid">{modelChecks.map((item) => <li key={item}>{item}</li>)}</ul><section className="elsa-link-card"><div><p className="eyebrow">Официальный источник</p><h3>Каталог Elsa Babe</h3><p>На официальном сайте можно заранее посмотреть доступные тела, головы, варианты внешности и возможную комплектацию.</p><p className="elsa-note">Наличие конкретной модели, головы или опции необходимо подтверждать у продавца перед созданием заказа.</p></div><a className="button secondary" href={officialUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть каталог Elsa Babe на официальном сайте в новой вкладке">Открыть каталог</a></section></div></div></section>

        <section className="section"><div className="container elsa-step-layout"><div className="elsa-step-number">02</div><div><p className="eyebrow">Торговая площадка</p><h2>Магазин Elsa Babe на AliExpress</h2><p>Покупка может оформляться через магазин Elsa Babe на AliExpress.</p><p>Перед заказом рекомендуется не оплачивать товар сразу, а сначала написать продавцу, отправить ссылку на выбранную модель и уточнить порядок оформления.</p><a className="button primary elsa-store-button" href={aliexpressUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть магазин Elsa Babe на AliExpress в новой вкладке">Открыть магазин на AliExpress</a><div className="notice">Перед оплатой проверьте название магазина, данные продавца, ссылку, условия заказа и итоговую сумму. Страницы магазинов и правила торговой площадки могут меняться.</div></div></div></section>

        <section className="section alt"><div className="container elsa-two-column"><section className="elsa-content-card"><p className="eyebrow">Первичное обращение</p><h2>Связь с продавцом</h2><p>Первичное обращение можно отправить через чат AliExpress. Покупателю следует указать, какую модель Elsa Babe он хочет заказать, и приложить ссылки или изображения.</p><p>Дальнейшее согласование также может проходить по электронной почте: <a href={`mailto:${email}`} target="_blank" rel="noopener noreferrer nofollow" aria-label="Написать Elsa Babe по электронной почте">{email}</a>.</p><p>На почту можно отправить:</p><ul className="elsa-card-list">{emailDetails.map((item) => <li key={item}>{item}</li>)}</ul><div className="notice">Сохраняйте переписку, подтверждение конфигурации, итоговую цену и номер заказа.</div></section><section className="elsa-content-card elsa-confirm-card"><p className="eyebrow">До оплаты</p><h2>Согласование комплектации</h2><p>Письменно подтвердите все применимые параметры:</p><ul className="elsa-card-list">{configurationChecks.map((item) => <li key={item}>{item}</li>)}</ul><div className="elsa-emphasis"><strong>Письменное подтверждение</strong><span>Попросите продавца одним сообщением подтвердить полную итоговую конфигурацию. Это снижает риск путаницы между выбранным телом, головой, внешностью и дополнительными опциями.</span></div></section></div></section>

        <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Финальный расчёт</p><h2>Стоимость</h2></div><p>Базовая цена в карточке товара может не отражать выбранную конфигурацию.</p></div><p>Стоимость зависит от выбранной конфигурации и может заметно отличаться от базовой цены, показанной в карточке товара.</p><ul className="elsa-factor-grid">{priceFactors.map((item) => <li key={item}>{item}</li>)}</ul><div className="elsa-experience-card"><p className="eyebrow">Ориентир по опыту покупателей</p><h3>Примерно 120 000–180 000 рублей и выше</h3><p>По отдельным сообщениям покупателей, силиконовые модели могут обходиться примерно в этом диапазоне. В отдельных случаях итоговая цена может быть как ниже, так и значительно выше.</p><p><strong>Этот диапазон не является актуальным прайс-листом, официальной ценой или гарантией. Перед оплатой необходимо получить точный расчёт от продавца.</strong></p><a href={converterUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть конвертер юаня в рубли в новой вкладке">Конвертер юаня в рубли</a></div></div></section>

        <section className="section alt"><div className="container"><div className="section-head"><div><p className="eyebrow">Возможный сценарий</p><h2>Как проходит оплата через AliExpress</h2></div><p>Порядок необходимо подтверждать для конкретного заказа.</p></div><p>Для индивидуального заказа продавец может использовать специальный товар или карточку-«якорь».</p><ol className="elsa-order-steps">{paymentSteps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><p>{step}</p></li>)}</ol><div className="elsa-warning-panel"><strong>Перед оплатой</strong><ul>{paymentWarnings.map((item) => <li key={item}>{item};</li>)}</ul><a href={chinaTimeUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть текущее время в Китае в новой вкладке">Текущее время в Китае</a></div></div></section>

        <section className="section"><div className="container elsa-two-column"><section className="elsa-content-card"><p className="eyebrow">Контроль операции</p><h2>Безопасность оплаты</h2><p>Перед оплатой необходимо проверить:</p><ul className="elsa-card-list">{safetyChecks.map((item) => <li key={item}>{item}</li>)}</ul><div className="notice">Не переводите оплату способом, который не был заранее согласован и который лишает покупателя предусмотренных торговой площадкой механизмов защиты.</div><p className="elsa-note">AliExpress не гарантирует возврат средств в любой ситуации; действующие правила необходимо изучить до оплаты.</p></section><section className="elsa-content-card"><p className="eyebrow">Производственный этап</p><h2>Срок изготовления</h2><p>Срок изготовления зависит от выбранного тела, головы, сложности макияжа, дополнительных опций, загруженности производства и других факторов.</p><p>До оплаты необходимо запросить:</p><ul className="elsa-card-list">{productionChecks.map((item) => <li key={item}>{item}</li>)}</ul><p className="elsa-note">Универсальный срок изготовления для всех заказов не указывается.</p></section></div></section>

        <section className="section alt"><div className="container elsa-photo-layout"><div><p className="eyebrow">Контроль до отправки</p><h2>Заводские фотографии</h2><p>Перед отправкой рекомендуется запросить фотографии готового изделия.</p><p className="elsa-note">Ошибки или расхождения лучше обсуждать до отправки, когда исправление ещё может быть возможно. Предоставление фотографий необходимо заранее подтвердить у продавца.</p></div><div className="elsa-photo-checks"><strong>На фотографиях следует проверить</strong><ul>{photoChecks.map((item) => <li key={item}>{item}</li>)}</ul></div></div></section>

        <section className="section"><div className="container elsa-two-column"><section className="elsa-content-card"><p className="eyebrow">Логистика</p><h2>Доставка</h2><p>После оплаты доставка обычно оформляется через AliExpress на адрес покупателя.</p><p>В зависимости от региона и службы доставки посылка может быть доставлена по адресу, до пункта выдачи или через другую доступную логистическую схему.</p><p>Перед получением заранее продумайте:</p><ul className="elsa-card-list">{deliveryPreparation.map((item) => <li key={item}>{item}</li>)}</ul><div className="elsa-emphasis"><strong>Тяжёлая посылка</strong><span>Полноразмерная кукла вместе с коробкой может иметь значительный вес. Не следует рассчитывать, что такую посылку удастся безопасно перенести одному человеку без подготовки.</span></div></section><section className="elsa-content-card"><p className="eyebrow">Первичная проверка</p><h2>Получение посылки</h2><ul className="elsa-receiving-list">{receivingChecks.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ul><p className="elsa-note">Порядок подачи претензии и допустимые сроки необходимо проверять в правилах AliExpress и условиях продавца на момент покупки.</p></section></div></section>

        <section className="section alt"><div className="container"><div className="elsa-neutral-panel"><p className="eyebrow">Параметр конкретного тела</p><h2>Важный параметр: внутренний канал</h2><p>По опыту некоторых покупателей, у отдельных моделей Elsa Babe внутренний канал может быть достаточно узким.</p><p>Если этот параметр имеет значение, его необходимо обсудить с продавцом до оплаты.</p><div className="elsa-neutral-grid">{internalChecks.map((item) => <span key={item}>{item}</span>)}</div><div className="notice">Размеры и конструктивные особенности зависят от конкретного тела. После изготовления изменить такие параметры может быть сложно или невозможно.</div><p className="elsa-note">Сообщения отдельных покупателей не являются характеристикой всех моделей Elsa Babe.</p></div></div></section>

        <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Полный чек-лист</p><h2>Что проверить перед заказом</h2></div><p>Сохраните подтверждения по всем применимым пунктам.</p></div><ol className="elsa-final-checklist">{finalChecks.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></div></section>

        <section className="section alt"><div className="container"><div className="section-head"><div><p className="eyebrow">Проверенные направления</p><h2>Контакты и ссылки</h2></div><p>Проверяйте актуальность страниц и данных непосредственно перед заказом.</p></div><div className="elsa-contact-grid"><a href={officialUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть официальный сайт Elsa Babe в новой вкладке"><span>Официальный сайт Elsa Babe</span><strong>elsababedoll.com</strong><small>Открыть</small></a><a href={aliexpressUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть магазин Elsa Babe на AliExpress в новой вкладке"><span>Магазин Elsa Babe на AliExpress</span><strong>AliExpress</strong><small>Открыть</small></a><a href={`mailto:${email}`} target="_blank" rel="noopener noreferrer nofollow" aria-label="Написать Elsa Babe по электронной почте"><span>E-mail</span><strong>{email}</strong><small>Написать</small></a><a href={converterUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть конвертер юаня в рубли в новой вкладке"><span>Конвертер валют</span><strong>Юань в рубли</strong><small>Открыть</small></a><a href={chinaTimeUrl} target="_blank" rel="noopener noreferrer nofollow" aria-label="Открыть текущее время в Китае в новой вкладке"><span>Время в Китае</span><strong>Текущий часовой пояс</strong><small>Открыть</small></a></div></div></section>

        <section className="section"><div className="container"><div className="elsa-disclaimer"><p className="eyebrow">Справочная информация · 18+</p><h2>Важное предупреждение</h2><p>Anime Dolls World публикует эту инструкцию исключительно в справочных целях.</p><ul><li>Сайт не является продавцом Elsa Babe.</li><li>Не является представителем AliExpress.</li><li>Не принимает оплату.</li><li>Не участвует в оформлении заказа.</li><li>Не является стороной сделки.</li><li>Не отвечает за действия магазина, продавца или торговой площадки.</li><li>Не несёт ответственности за изготовление, доставку, сроки, таможню и дополнительные расходы.</li><li>Не гарантирует актуальность цен, ссылок, условий и доступность моделей.</li><li>Не гарантирует результат спора, возврата или компенсации.</li></ul><p>Все финансовые операции покупатель совершает самостоятельно и непосредственно через выбранный способ оформления заказа.</p><p><strong>Перед оплатой необходимо проверить магазин, продавца, ссылку, итоговую комплектацию, сумму, адрес доставки и действующие правила AliExpress.</strong></p><p>Тематика страницы относится к товарам для совершеннолетней аудитории.</p></div></div></section>
      </article>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageJsonLd) }} />
    </>
  );
}
